### ISSUE TITLE
plot.solist with equal.ribbon=TRUE uses the ribbon of the first item in list only

### ISSUE THREAD

**Issue by tshearm** [spatstat/spatstat.geom#15]
I have a list of images created using solist and when I try to plot them with ribbon=TRUE the ribbon only contains the color map of the first image in the list. See the resulting attached image for example. Notice that the species corresponding to the lavender color in years after 1994 is not included in the ribbon. If I change the order of the list the ribbon will change.

This might be as intended but is there a way to have the ribbon include all species?

[Dominant_small_.pdf](https://github.com/spatstat/spatstat.geom/files/10339833/Dominant_small_.pdf)

**Comment by rubak** [comment]
Thanks for pointing this out. We will have to think a bit about the problem and get back to you. Your pixel values are character valued and as a first thought it may have been easier if you used a factor as you can have unused levels in a factor. However, `spatstat` handles a `solist` of factor valued images even worse than your case, so that won’t help you for now.

``` r
library(spatstat)
v <- gorillas.extra$vegetation
plot(solist(v, v))
```

![](https://i.imgur.com/XgGneCb.png)

``` r
plot(solist(v, v), equal.ribbon = TRUE)
#> Error in Summary.factor(structure(c(NA, NA, NA, NA, NA, NA, NA, NA, NA, : 'range' not meaningful for factors
```

**Comment by baddstats** [comment]
You're asking for the plotting code to recognise a situation where the images are factors with different sets of factor levels for each image, and to match and merge the levels to obtain a new list of factor images that each use the same levels. This is a lot to expect the plotting code to do. But I will write a stand-alone function that merges the factor levels, then invoke this in the plot code.

**Comment by baddstats** [comment]
This is now fixed, in the development version `spatstat.geom 3.0-4.002`

**Comment by tshearm** [comment]
Thanks! You all do great work!
